services:
    UKMNorge\DesignBundle\Twig\AppExtension:
        public: false
        tags: ['twig.extension']
    UKMNorge\DesignBundle\Services\UKMDesign:
        public: true
        arguments:
            - "@file_locator"
            - '%kernel.cache_dir%'
            - '%kernel.project_dir%'
            #- '%ukm_design.section_id%'
            #- '%ukm_design.section_name%'
            #- '%ukm_design.section_url%'
