services:
    UKMNorge\DesignBundle\Twig\AppExtension:
        public: false
        tags: ['twig.extension']
    UKMNorge\UKMDesign\Services\UKMDesign:
        public: true
        arguments:
            - "@file_locator"
            - '%kernel.cache_dir%'
            - '%kernel.project_dir%'
